version: '3.8'

networks:
  gv_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:

  postgres: 
    container_name: gestao_vagas_postgres
    image: postgres:latest
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas
      -
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv_network
    ports:
      - 9090:9090

  granafa:
    container_name: granafa
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - gv_network